version: '3.9'

services:
  api_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_service
    ports:
      - 8080:0420
    networks:
      - custom_network

networks:
  custom_network:  
    external: true  

